#!/usr/bin/env python3
#  NOCA -- Next Online Contest Administrator
#  Copyright (c) 2026 Daniel Correa Lobato <daniel@lobato.org>
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

"""Bulk-seed Arena users with randomised Faker data.

All generated users are enabled, email-confirmed, and over 18 years old.
Country and subdivision are picked at random from ISO 3166-1/-2 via pycountry.
The user's name is generated by a locale-aware Faker instance matched to the
chosen country (e.g. Japan → ja_JP, Italy → it_IT).

Usage:
    uv run python scripts/arena/seed_arena_users_bulk.py -n 50
    uv run python scripts/arena/seed_arena_users_bulk.py -n 100 --password secret123
    uv run python scripts/arena/seed_arena_users_bulk.py -n 5 --role ARENA_ADMIN
    uv run python scripts/arena/seed_arena_users_bulk.py -n 50 --random-affiliation
"""

from __future__ import annotations

import argparse
import asyncio
import logging
import random
import sys
import uuid
from datetime import UTC, datetime
from functools import cache

import pycountry
from dotenv import load_dotenv
from faker import Faker
from secrets_manager import SecretsConfig, SecretsManager
from sqlalchemy import select
from sqlalchemy.pool import NullPool

from arena.config import settings as arena_settings
from arena.database import create_engine, create_session_factory
from arena.models.arena_affiliations import ArenaAffiliation
from arena.models.arena_users import ArenaUser
from shared.app_logging import configure_logging
from shared.db_schema.custom_types import init_encrypted_string
from shared.enumerations import ArenaRole

logger = logging.getLogger(__name__)

# ISO 3166-1 alpha-2 → Faker locale.  Countries absent from this map fall back
# to "en_US" so names at least look plausible.
_COUNTRY_LOCALE: dict[str, str] = {
    "AE": "ar_AE",
    "AL": "sq_AL",
    "AM": "hy_AM",
    "AR": "es_AR",
    "AT": "de_AT",
    "AU": "en_AU",
    "AZ": "az_AZ",
    "BA": "bs_BA",
    "BD": "bn_BD",
    "BE": "nl_BE",
    "BG": "bg_BG",
    "BH": "ar_BH",
    "BR": "pt_BR",
    "CA": "en_CA",
    "CH": "de_CH",
    "CL": "es_CL",
    "CN": "zh_CN",
    "CO": "es_CO",
    "CY": "el_CY",
    "CZ": "cs_CZ",
    "DE": "de_DE",
    "DK": "da_DK",
    "DZ": "ar_DZ",
    "EE": "et_EE",
    "EG": "ar_EG",
    "ES": "es_ES",
    "ET": "am_ET",
    "FI": "fi_FI",
    "FR": "fr_FR",
    "GB": "en_GB",
    "GE": "ka_GE",
    "GH": "tw_GH",
    "GR": "el_GR",
    "HR": "hr_HR",
    "HU": "hu_HU",
    "ID": "id_ID",
    "IE": "en_IE",
    "IL": "he_IL",
    "IN": "hi_IN",
    "IR": "fa_IR",
    "IS": "is_IS",
    "IT": "it_IT",
    "JO": "ar_JO",
    "JP": "ja_JP",
    "KE": "en_KE",
    "KR": "ko_KR",
    "LI": "de_LI",
    "LT": "lt_LT",
    "LU": "lb_LU",
    "LV": "lv_LV",
    "MT": "mt_MT",
    "MX": "es_MX",
    "NG": "en_NG",
    "NL": "nl_NL",
    "NO": "no_NO",
    "NP": "ne_NP",
    "NZ": "en_NZ",
    "PH": "fil_PH",
    "PK": "en_PK",
    "PL": "pl_PL",
    "PS": "ar_PS",
    "PT": "pt_PT",
    "RO": "ro_RO",
    "RU": "ru_RU",
    "SA": "ar_SA",
    "SE": "sv_SE",
    "SI": "sl_SI",
    "SK": "sk_SK",
    "TH": "th_TH",
    "TR": "tr_TR",
    "TW": "zh_TW",
    "UA": "uk_UA",
    "US": "en_US",
    "UZ": "uz_UZ",
    "VN": "vi_VN",
    "ZA": "zu_ZA",
}


@cache
def _faker_for_locale(locale: str) -> Faker:
    """Return a cached Faker instance for *locale*.

    Args:
        locale: A Faker locale string such as ``"it_IT"``.

    Returns:
        Faker: Cached locale-specific instance.
    """
    return Faker(locale)


def _utcnow() -> datetime:
    return datetime.now(UTC)


def _random_country_and_subdivision() -> tuple[str, str | None, str]:
    """Return a random country code, optional subdivision code, and Faker locale.

    Returns:
        tuple[str, str | None, str]: (country_code, subdivision_code, faker_locale)
    """
    countries = list(pycountry.countries)
    country = random.choice(countries)
    country_code: str = country.alpha_2  # type: ignore[attr-defined]
    locale = _COUNTRY_LOCALE.get(country_code, "en_US")

    raw_subdivisions = pycountry.subdivisions.get(country_code=country_code)  # type: ignore[no-untyped-call]
    subdivisions = list(raw_subdivisions) if raw_subdivisions else []
    if subdivisions:
        sub = random.choice(subdivisions)
        return country_code, str(sub.code), locale  # type: ignore[attr-defined]
    return country_code, None, locale


def _build_user(password: str, role: ArenaRole, affiliation_ids: list[str]) -> ArenaUser:
    """Build a new ArenaUser instance populated with Faker data.

    The user's name is generated with a locale-aware Faker instance matched to
    the randomly selected country (e.g. Japan → ``ja_JP``).

    Args:
        password: Plain-text password to assign.
        role: Arena role to assign to the user.
        affiliation_ids: Pool of affiliation IDs to pick from at random.
            Pass an empty list to leave affiliation unset.

    Returns:
        ArenaUser: Unsaved ORM instance.
    """
    now = _utcnow()
    country_code, subdivision_code, locale = _random_country_and_subdivision()
    name_fake = _faker_for_locale(locale)

    user = ArenaUser()
    user.id = str(uuid.uuid4())
    user.nome = name_fake.name()
    user.dta_nascimento = name_fake.date_of_birth(minimum_age=18, maximum_age=40)
    user.role = role
    user.session_version = 1
    user.consentimento_responsavel = True
    user.dta_consentimento_responsavel = now
    user.aceitou_termos_privacidade = True
    user.dta_aceitacao_termos_privacidade = now
    user.usa_2fa = False
    user.com_foto = False
    user.precisa_trocar_senha = False
    user.ativo = True
    user.dta_ativacao_conta = now
    user.email_confirmado = True
    user.dta_validacao_email = now
    user.country_code = country_code
    user.subdivision_code = subdivision_code
    user.affiliation_id = random.choice(affiliation_ids) if affiliation_ids else None
    user.prefered_language = random.choice(["en-US", "pt-BR"])
    user.ai_backend_credits = 0
    user.created_at = now
    user.updated_at = now

    # email setter normalises and stores email_normalizado
    user.email = name_fake.ascii_free_email()
    # password setter hashes via Werkzeug
    user.password = password

    return user


async def seed_users(count: int, password: str, role: ArenaRole, random_affiliation: bool) -> None:
    """Insert *count* randomised Arena users into the database.

    Args:
        count: Number of users to create.
        password: Plain-text password shared by all seeded users.
        role: Arena role assigned to all seeded users.
        random_affiliation: When True, assign a random existing affiliation to
            each user.  If no affiliations exist in the database, users are
            created without one regardless of this flag.
    """
    load_dotenv(arena_settings.ARENA_CRYPTO_ENV_FILE, override=False)
    secrets_config = SecretsConfig.from_environment()
    secrets_manager = SecretsManager(secrets_config)
    init_encrypted_string(secrets_manager)

    engine = create_engine(arena_settings.db_url, poolclass=NullPool)
    session_factory = create_session_factory(engine)

    created = 0
    try:
        async with session_factory() as session:
            affiliation_ids: list[str] = []
            if random_affiliation:
                rows = await session.execute(select(ArenaAffiliation.id))
                affiliation_ids = list(rows.scalars().all())
                if not affiliation_ids:
                    logger.warning("No affiliations found in database; users will have no affiliation")

            for i in range(count):
                user = _build_user(password, role, affiliation_ids)
                session.add(user)
                logger.info("Queued user %d/%d — %s <%s>", i + 1, count, user.nome, user.email)
            await session.commit()
            created = count
    finally:
        await engine.dispose()

    print(f"SUCCESS: {created} Arena user(s) created with role '{role}' and password '{password}'")


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments.

    Returns:
        argparse.Namespace: Parsed arguments.
    """
    parser = argparse.ArgumentParser(description="Bulk-seed randomised Arena users.")
    parser.add_argument(
        "-n",
        type=int,
        required=True,
        metavar="COUNT",
        help="Number of users to create",
    )
    parser.add_argument(
        "--password",
        default="password123",
        help="Plain-text password for all created users (default: password123)",
    )
    parser.add_argument(
        "--role",
        default=ArenaRole.ARENA_USER,
        choices=[r.value for r in ArenaRole],
        help="Role for all created users (default: ARENA_USER)",
    )
    parser.add_argument(
        "--random-affiliation",
        action="store_true",
        default=False,
        help="Assign a random existing affiliation to each user (skipped if none exist)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    configure_logging(logging_level=logging.INFO)
    args = parse_args()

    if args.n < 1:
        print("ERROR: -n must be a positive integer", file=sys.stderr)
        sys.exit(1)

    asyncio.run(
        seed_users(
            count=args.n,
            password=args.password,
            role=ArenaRole(args.role),
            random_affiliation=args.random_affiliation,
        )
    )
    sys.exit(0)
