#  NOCA -- Next Online Contest Administrator
#  Copyright (c) 2026 The NOCA Authors (see AUTHORS)
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

subject = "Your credentials for contest {contest_name}"
body = """
Yo, {fullname}!

These are your credentials for connecting on contest {contest_name} running on {brand_name}.

Login page: {contest_login_url}
username: {username}
password: {password}

Remember to replace your password as soon as possible!

Looking forward to see you! Best,
{sender_name}
"""
