#  NOCA -- Next Online Contest Administrator
#  Copyright (c) 2026 The NOCA Authors (see AUTHORS)
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

subject = "Your {brand_name} global administrator credentials"
body = """
Yo, {fullname}!

These are your {brand_name} global administrator credentials.

Login page: {login_url}
username: {username}
password: {password}

Remember to replace your password as soon as possible!

Best,
{sender_name}
"""
