"""add compiler/interpreter version to language list

Revision ID: e00815b4118a
Revises: 202604231600
Create Date: 2026-04-25 00:59:49.880381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00815b4118a'
down_revision: Union[str, Sequence[str], None] = '202604231600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('version', sa.String(length=128), nullable=True, comment="version of compiler/interpreter used, e.g. 'gcc version 12.2.0 (Debian 12.2.0-14+deb12u1)'"))
    op.alter_column('problem_language_limits', 'repetitions',
               existing_type=sa.INTEGER(),
               comment='Number of executions sharing the total time budget for this problem/language pair.',
               existing_nullable=False)
    op.alter_column('problem_limit_change_batch_languages', 'change_kind',
               existing_type=sa.VARCHAR(length=16),
               comment="'explicit' for override changes, 'fallback' otherwise.",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problem_limit_change_batch_languages', 'change_kind',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment="'explicit' for override changes, 'fallback' otherwise.",
               existing_nullable=False)
    op.alter_column('problem_language_limits', 'repetitions',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of executions sharing the total time budget for this problem/language pair.',
               existing_nullable=False)
    op.drop_column('languages', 'version')
    # ### end Alembic commands ###
