"""add arena problem categories

Revision ID: 364f67aa423f
Revises: 202605221200
Create Date: 2026-05-22 22:27:18.827505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '364f67aa423f'
down_revision: Union[str, Sequence[str], None] = '202605221200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_problem_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Human-readable category name shown to users.'),
    sa.Column('slug', sa.String(length=128), nullable=False, comment='URL-safe identifier for the category (lowercase, hyphens).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('arena_problem_category_map',
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['arena_problem_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problem_id'], ['arena_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('problem_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arena_problem_category_map')
    op.drop_table('arena_problem_categories')
    # ### end Alembic commands ###
