"""add arena_ai_batch_jobs table

Revision ID: 622c33190b72
Revises: 202605250001
Create Date: 2026-05-25 22:32:05.992547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622c33190b72'
down_revision: Union[str, Sequence[str], None] = '202605250001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arena_ai_batch_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False, comment='1:1 FK to arena_submissions. UNIQUE enforces at most one batch job per submission.'),
    sa.Column('openai_batch_id', sa.String(length=128), nullable=False, comment="OpenAI batch identifier, e.g. 'batch_xxx'. Returned by batches.create()."),
    sa.Column('local_status', sa.String(length=32), server_default='preparing', nullable=False, comment='Local state machine: preparing, submitted, polling, completed, failed, expired, cancelled. See ArenaAIBatchJobStatus enum.'),
    sa.Column('openai_status', sa.String(length=32), nullable=True, comment='Last known OpenAI batch status verbatim: validating, in_progress, finalizing, completed, failed, expired, cancelling, cancelled.'),
    sa.Column('input_file_id', sa.String(length=128), nullable=True, comment='OpenAI JSONL batch input file ID. Deleted on terminal status.'),
    sa.Column('code_file_id', sa.String(length=128), nullable=True, comment='OpenAI uploaded source-code file ID. Deleted on terminal status.'),
    sa.Column('statement_file_id', sa.String(length=128), nullable=True, comment='OpenAI uploaded problem-statement file ID. Deleted on terminal status.'),
    sa.Column('error_file_id', sa.String(length=128), nullable=True, comment='OpenAI error output file ID, populated when the completed batch has failed lines.'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message from OpenAI or local processing.'),
    sa.Column('request_counts_total', sa.Integer(), nullable=True, comment='Total request count reported by the OpenAI batch object.'),
    sa.Column('request_counts_completed', sa.Integer(), nullable=True, comment='Completed request count reported by the OpenAI batch object.'),
    sa.Column('request_counts_failed', sa.Integer(), nullable=True, comment='Failed request count reported by the OpenAI batch object.'),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent poller check for this batch.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when terminal local_status was reached.'),
    sa.ForeignKeyConstraint(['submission_id'], ['arena_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openai_batch_id'),
    sa.UniqueConstraint('submission_id')
    )
    op.alter_column('arena_submission_ai_reviews', 'used_platform_key',
               existing_type=sa.BOOLEAN(),
               comment="True when the platform API key was used for this review; False when the user's own key was used",
               existing_comment="True when the platform API key was used for this review; False when the user's own API key was used",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arena_submission_ai_reviews', 'used_platform_key',
               existing_type=sa.BOOLEAN(),
               comment="True when the platform API key was used for this review; False when the user's own API key was used",
               existing_comment="True when the platform API key was used for this review; False when the user's own key was used",
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('arena_ai_batch_jobs')
    # ### end Alembic commands ###
