"""arena: Sync column comments and drop redundant email_normalizado index.

Revision ID: a5c71ab130e5
Revises: b6bade6eebf0
Create Date: 2026-05-19 17:25:40.188802

"""

#  NOCA -- Next Online Contest Administrator
#  Copyright (c) 2026 Daniel Correa Lobato <daniel@lobato.org>
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a5c71ab130e5"
down_revision: str | Sequence[str] | None = "b6bade6eebf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add arena column comments and drop redundant email_normalizado index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "arena_affiliations",
        "name",
        existing_type=sa.VARCHAR(length=200),
        comment="Affiliation display name",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_affiliations",
        "country_code",
        existing_type=sa.VARCHAR(length=2),
        comment="ISO 3166-1 alpha-2 country code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "subdivision_code",
        existing_type=sa.VARCHAR(length=16),
        comment="ISO 3166-2 subdivision code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "url",
        existing_type=sa.VARCHAR(length=500),
        comment="Affiliation public URL",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "logo_base64",
        existing_type=sa.TEXT(),
        comment="Affiliation logo stored as base64-encoded image bytes",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "logo_mime",
        existing_type=sa.VARCHAR(length=129),
        comment="MIME type of the affiliation logo",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_backup_2fa",
        "arena_user_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Arena user who owns this backup code",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_backup_2fa",
        "hash_codigo",
        existing_type=sa.VARCHAR(length=256),
        comment="Werkzeug hash of the one-time backup code",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_backup_2fa",
        "utilizado",
        existing_type=sa.BOOLEAN(),
        comment="True when this backup code has already been consumed",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_backup_2fa",
        "dta_uso",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when this code was consumed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_backup_2fa",
        "dta_para_remocao",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Scheduled deletion timestamp for used codes",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "arena_user_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Arena user who performed this login",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_login_history",
        "dta_login",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of the login event",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_login_history",
        "ip_address",
        existing_type=sa.VARCHAR(length=45),
        comment="Client IP address (IPv4 or IPv6)",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "location",
        existing_type=sa.VARCHAR(length=128),
        comment="Geographic location derived from IP",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "user_agent",
        existing_type=sa.TEXT(),
        comment="HTTP User-Agent header",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "mode",
        existing_type=sa.VARCHAR(length=32),
        comment="Authentication method used: password, 2fa, backup_code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_problem_solvers",
        "solved_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of the first accepted submission for this (user, problem) pair.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_problem_tried",
        "last_tried_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Updated on each new submission. ON CONFLICT DO UPDATE at the service layer.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_problems",
        "time_limit_ms",
        existing_type=sa.INTEGER(),
        comment="Time limit in milliseconds; no per-language overrides for arena problems.",
        existing_nullable=False,
        existing_server_default=sa.text("1000"),
    )
    op.alter_column(
        "arena_problems",
        "memory_limit_kb",
        existing_type=sa.INTEGER(),
        comment="Memory limit in KB enforced by cgroup.",
        existing_nullable=False,
        existing_server_default=sa.text("262144"),
    )
    op.alter_column(
        "arena_problems",
        "pids_limit",
        existing_type=sa.INTEGER(),
        comment="Max processes/threads via cgroup pids controller.",
        existing_nullable=False,
        existing_server_default=sa.text("64"),
    )
    op.alter_column(
        "arena_problems",
        "output_limit_in_bytes",
        existing_type=sa.INTEGER(),
        comment="Max stdout bytes.",
        existing_nullable=False,
        existing_server_default=sa.text("65536"),
    )
    op.alter_column(
        "arena_problems",
        "source",
        existing_type=sa.VARCHAR(length=256),
        comment="Origin of the problem, e.g. contest name.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_problems",
        "problem_image_base64",
        existing_type=sa.TEXT(),
        comment="BASE-64 encoded image for the statement.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_submission_judgments",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment="JudgmentStatus: QUEUED, DISPATCHED, JUDGING, DONE, FAILED, SUPERSEDED.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_submission_judgments",
        "autojudge_verdict",
        existing_type=sa.VARCHAR(length=10),
        comment="Verdict set by the autojudge worker.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_submission_judgments",
        "final_verdict",
        existing_type=sa.VARCHAR(length=10),
        comment="Equals autojudge_verdict; no human confirmation step in arena.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_submission_judgments",
        "error_message",
        existing_type=sa.TEXT(),
        comment="Internal judge error message.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_submission_test_results",
        "verdict",
        existing_type=sa.VARCHAR(length=10),
        comment="Verdict enum value for this test case.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_submissions",
        "language_id",
        existing_type=sa.VARCHAR(length=64),
        comment="Language key, e.g. 'gcc-c17'. String(64) matches languages.id definition.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_submissions",
        "source_hash",
        existing_type=sa.VARCHAR(length=64),
        comment=("SHA-256 hex digest of source_code. No uniqueness constraint: arena allows duplicate submits."),
        existing_nullable=False,
    )
    op.alter_column(
        "arena_test_cases",
        "ordinal",
        existing_type=sa.INTEGER(),
        comment="1-based execution order within the problem.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_test_cases",
        "is_sample",
        existing_type=sa.BOOLEAN(),
        comment="Sample cases are shown to contestants; secret cases are not.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "nome",
        existing_type=sa.VARCHAR(length=120),
        comment="Full display name of the arena user",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_users", "dta_nascimento", existing_type=sa.DATE(), comment="Date of birth", existing_nullable=True
    )
    op.alter_column(
        "arena_users",
        "email_normalizado",
        existing_type=sa.VARCHAR(length=180),
        comment="Normalised email address; used as the primary login identifier",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_users",
        "email_responsavel_legal",
        existing_type=sa.VARCHAR(length=255),
        comment="Parent or legal guardian email for users who require consent",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "consentimento_responsavel",
        existing_type=sa.BOOLEAN(),
        comment="Parent or legal guardian consent has been confirmed",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "dta_consentimento_responsavel",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when parent or legal guardian consent was confirmed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "password_hash",
        existing_type=sa.VARCHAR(length=256),
        comment="Werkzeug password hash",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_users",
        "role",
        existing_type=postgresql.ENUM("ARENA_ADMIN", "ARENA_JUDGE", "ARENA_USER", name="arenarole"),
        comment="Arena role: ARENA_ADMIN, ARENA_JUDGE, or ARENA_USER",
        existing_nullable=False,
        existing_server_default=sa.text("'ARENA_USER'::arenarole"),
    )
    op.alter_column(
        "arena_users",
        "ativo",
        existing_type=sa.BOOLEAN(),
        comment="Account is active; user is allowed to log in",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "dta_ativacao_conta",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the account was activated",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "email_confirmado",
        existing_type=sa.BOOLEAN(),
        comment="Email address has been confirmed; required before first login",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "dta_validacao_email",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the email address was confirmed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "dta_ultima_alteracao_senha",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of the last password change",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "ultimo_login",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of the most recent successful login",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "com_foto",
        existing_type=sa.BOOLEAN(),
        comment="True when the user has uploaded a profile photo",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "foto_base64",
        existing_type=sa.TEXT(),
        comment="Original photo stored as base64-encoded string",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "avatar_base64",
        existing_type=sa.TEXT(),
        comment="Resized avatar derived from the original photo, base64-encoded",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "foto_mime",
        existing_type=sa.VARCHAR(length=129),
        comment="MIME type of the stored photo (e.g. image/jpeg)",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "dta_foto",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of the last photo upload",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "usa_2fa",
        existing_type=sa.BOOLEAN(),
        comment="TOTP two-factor authentication is enabled for this account",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "dta_mudanca_2fa",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when 2FA was last enabled or disabled",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "_otp_secret",
        existing_type=sa.VARCHAR(length=500),
        comment="Encrypted TOTP secret used for 2FA code generation",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "ultimo_otp",
        existing_type=sa.VARCHAR(length=6),
        comment="Last used OTP code; prevents replay attacks within the same time window",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "precisa_trocar_senha",
        existing_type=sa.BOOLEAN(),
        comment="Forces a password change on the next login",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "dta_marcacao_troca_senha",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the forced password change flag was set",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "session_version",
        existing_type=sa.INTEGER(),
        comment=("Incremented on each password change; JWT tokens carrying an older version are rejected"),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "arena_users",
        "dta_rating_update",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when the user's rating was computed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "user_rating",
        existing_type=sa.INTEGER(),
        comment="User's rating computed",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "arena_users",
        "solved_problems",
        existing_type=sa.INTEGER(),
        comment="Number of problems solved",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "arena_users",
        "country_code",
        existing_type=sa.VARCHAR(length=2),
        comment="ISO 3166-1 alpha-2 country code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "subdivision_code",
        existing_type=sa.VARCHAR(length=16),
        comment="ISO 3166-2 subdivision code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "affiliation_id",
        existing_type=sa.VARCHAR(length=36),
        comment="Optional affiliation selected by the Arena user",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_arena_users_email_normalizado"), table_name="arena_users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove column comments from arena tables; recreate the non-unique email_normalizado index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_arena_users_email_normalizado"), "arena_users", ["email_normalizado"], unique=False)
    op.alter_column(
        "arena_users",
        "affiliation_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Optional affiliation selected by the Arena user",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "subdivision_code",
        existing_type=sa.VARCHAR(length=16),
        comment=None,
        existing_comment="ISO 3166-2 subdivision code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "country_code",
        existing_type=sa.VARCHAR(length=2),
        comment=None,
        existing_comment="ISO 3166-1 alpha-2 country code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "solved_problems",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Number of problems solved",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "arena_users",
        "user_rating",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="User's rating computed",
        existing_nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "arena_users",
        "dta_rating_update",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when the user's rating was computed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "session_version",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment=("Incremented on each password change; JWT tokens carrying an older version are rejected"),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "arena_users",
        "dta_marcacao_troca_senha",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when the forced password change flag was set",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "precisa_trocar_senha",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Forces a password change on the next login",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "ultimo_otp",
        existing_type=sa.VARCHAR(length=6),
        comment=None,
        existing_comment="Last used OTP code; prevents replay attacks within the same time window",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "_otp_secret",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Encrypted TOTP secret used for 2FA code generation",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "dta_mudanca_2fa",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when 2FA was last enabled or disabled",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "usa_2fa",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="TOTP two-factor authentication is enabled for this account",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "dta_foto",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of the last photo upload",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "foto_mime",
        existing_type=sa.VARCHAR(length=129),
        comment=None,
        existing_comment="MIME type of the stored photo (e.g. image/jpeg)",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "avatar_base64",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Resized avatar derived from the original photo, base64-encoded",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "foto_base64",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Original photo stored as base64-encoded string",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "com_foto",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="True when the user has uploaded a profile photo",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "ultimo_login",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of the most recent successful login",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "dta_ultima_alteracao_senha",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of the last password change",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "dta_validacao_email",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when the email address was confirmed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "email_confirmado",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Email address has been confirmed; required before first login",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "dta_ativacao_conta",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when the account was activated",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "ativo",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Account is active; user is allowed to log in",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "role",
        existing_type=postgresql.ENUM("ARENA_ADMIN", "ARENA_JUDGE", "ARENA_USER", name="arenarole"),
        comment=None,
        existing_comment="Arena role: ARENA_ADMIN, ARENA_JUDGE, or ARENA_USER",
        existing_nullable=False,
        existing_server_default=sa.text("'ARENA_USER'::arenarole"),
    )
    op.alter_column(
        "arena_users",
        "password_hash",
        existing_type=sa.VARCHAR(length=256),
        comment=None,
        existing_comment="Werkzeug password hash",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_users",
        "dta_consentimento_responsavel",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when parent or legal guardian consent was confirmed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "consentimento_responsavel",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Parent or legal guardian consent has been confirmed",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_users",
        "email_responsavel_legal",
        existing_type=sa.VARCHAR(length=255),
        comment=None,
        existing_comment="Parent or legal guardian email for users who require consent",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "email_normalizado",
        existing_type=sa.VARCHAR(length=180),
        comment=None,
        existing_comment="Normalised email address; used as the primary login identifier",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_users",
        "dta_nascimento",
        existing_type=sa.DATE(),
        comment=None,
        existing_comment="Date of birth",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_users",
        "nome",
        existing_type=sa.VARCHAR(length=120),
        comment=None,
        existing_comment="Full display name of the arena user",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_test_cases",
        "is_sample",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Sample cases are shown to contestants; secret cases are not.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_test_cases",
        "ordinal",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="1-based execution order within the problem.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_submissions",
        "source_hash",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment=(
            "SHA-256 hex digest of source_code. No uniqueness constraint: arena allows duplicate submits."
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "arena_submissions",
        "language_id",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Language key, e.g. 'gcc-c17'. String(64) matches languages.id definition.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_submission_test_results",
        "verdict",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="Verdict enum value for this test case.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_submission_judgments",
        "error_message",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Internal judge error message.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_submission_judgments",
        "final_verdict",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="Equals autojudge_verdict; no human confirmation step in arena.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_submission_judgments",
        "autojudge_verdict",
        existing_type=sa.VARCHAR(length=10),
        comment=None,
        existing_comment="Verdict set by the autojudge worker.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_submission_judgments",
        "status",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment="JudgmentStatus: QUEUED, DISPATCHED, JUDGING, DONE, FAILED, SUPERSEDED.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_problems",
        "problem_image_base64",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="BASE-64 encoded image for the statement.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_problems",
        "source",
        existing_type=sa.VARCHAR(length=256),
        comment=None,
        existing_comment="Origin of the problem, e.g. contest name.",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_problems",
        "output_limit_in_bytes",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Max stdout bytes.",
        existing_nullable=False,
        existing_server_default=sa.text("65536"),
    )
    op.alter_column(
        "arena_problems",
        "pids_limit",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Max processes/threads via cgroup pids controller.",
        existing_nullable=False,
        existing_server_default=sa.text("64"),
    )
    op.alter_column(
        "arena_problems",
        "memory_limit_kb",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Memory limit in KB enforced by cgroup.",
        existing_nullable=False,
        existing_server_default=sa.text("262144"),
    )
    op.alter_column(
        "arena_problems",
        "time_limit_ms",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Time limit in milliseconds; no per-language overrides for arena problems.",
        existing_nullable=False,
        existing_server_default=sa.text("1000"),
    )
    op.alter_column(
        "arena_problem_tried",
        "last_tried_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Updated on each new submission. ON CONFLICT DO UPDATE at the service layer.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_problem_solvers",
        "solved_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of the first accepted submission for this (user, problem) pair.",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_login_history",
        "mode",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="Authentication method used: password, 2fa, backup_code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "user_agent",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="HTTP User-Agent header",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "location",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="Geographic location derived from IP",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "ip_address",
        existing_type=sa.VARCHAR(length=45),
        comment=None,
        existing_comment="Client IP address (IPv4 or IPv6)",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_login_history",
        "dta_login",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of the login event",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_login_history",
        "arena_user_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Arena user who performed this login",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_backup_2fa",
        "dta_para_remocao",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Scheduled deletion timestamp for used codes",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_backup_2fa",
        "dta_uso",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp when this code was consumed",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_backup_2fa",
        "utilizado",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="True when this backup code has already been consumed",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "arena_backup_2fa",
        "hash_codigo",
        existing_type=sa.VARCHAR(length=256),
        comment=None,
        existing_comment="Werkzeug hash of the one-time backup code",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_backup_2fa",
        "arena_user_id",
        existing_type=sa.VARCHAR(length=36),
        comment=None,
        existing_comment="Arena user who owns this backup code",
        existing_nullable=False,
    )
    op.alter_column(
        "arena_affiliations",
        "logo_mime",
        existing_type=sa.VARCHAR(length=129),
        comment=None,
        existing_comment="MIME type of the affiliation logo",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "logo_base64",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Affiliation logo stored as base64-encoded image bytes",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "url",
        existing_type=sa.VARCHAR(length=500),
        comment=None,
        existing_comment="Affiliation public URL",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "subdivision_code",
        existing_type=sa.VARCHAR(length=16),
        comment=None,
        existing_comment="ISO 3166-2 subdivision code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "country_code",
        existing_type=sa.VARCHAR(length=2),
        comment=None,
        existing_comment="ISO 3166-1 alpha-2 country code",
        existing_nullable=True,
    )
    op.alter_column(
        "arena_affiliations",
        "name",
        existing_type=sa.VARCHAR(length=200),
        comment=None,
        existing_comment="Affiliation display name",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
