"""squashed_schema

Revision ID: 73c77ae6a2b0
Revises:
Create Date: 2026-03-27 09:01:02.250471

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "73c77ae6a2b0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ROLE_VALUES = ("UBERADMIN", "ADMIN", "JUDGE", "STAFF", "TEAM", "USER")
_TASK_VALUES = ("BALLOON", "FIRST_BALLOON", "PRINT", "SOS")
_JUDGMENT_STATUS_VALUES = ("QUEUED", "DISPATCHED", "JUDGING", "DONE", "FAILED", "SUPERSEDED")
_VERDICT_VALUES = ("AC", "PE", "WA", "TLE", "MLE", "OLE", "RE", "CE")


def _create_role_enum() -> postgresql.ENUM:
    return postgresql.ENUM(*_ROLE_VALUES, name="roleenum")


def _role_enum_ref() -> postgresql.ENUM:
    return postgresql.ENUM(*_ROLE_VALUES, name="roleenum", create_type=False)


def _create_task_enum() -> postgresql.ENUM:
    return postgresql.ENUM(*_TASK_VALUES, name="taskenum")


def _task_enum_ref() -> postgresql.ENUM:
    return postgresql.ENUM(*_TASK_VALUES, name="taskenum", create_type=False)


def _create_judgment_status_enum() -> postgresql.ENUM:
    return postgresql.ENUM(*_JUDGMENT_STATUS_VALUES, name="judgmentstatus")


def _judgment_status_enum_ref() -> postgresql.ENUM:
    return postgresql.ENUM(*_JUDGMENT_STATUS_VALUES, name="judgmentstatus", create_type=False)


def _create_verdict_enum() -> postgresql.ENUM:
    return postgresql.ENUM(*_VERDICT_VALUES, name="verdict")


def _verdict_enum_ref() -> postgresql.ENUM:
    return postgresql.ENUM(*_VERDICT_VALUES, name="verdict", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    _create_role_enum().create(bind, checkfirst=True)
    _create_task_enum().create(bind, checkfirst=True)
    _create_judgment_status_enum().create(bind, checkfirst=True)
    _create_verdict_enum().create(bind, checkfirst=True)

    op.create_table(
        "languages",
        sa.Column("id", sa.String(length=64), nullable=False, comment="Language unique identifier, e.g. 'python3'"),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Language display name, e.g. 'Python 3'"),
        sa.Column(
            "compile_image",
            sa.String(length=255),
            nullable=False,
            comment="Docker image used for compilation, e.g. 'noca/judge-python3:compile'",
        ),
        sa.Column(
            "run_image",
            sa.String(length=255),
            nullable=False,
            comment="Docker image used for execution, e.g. 'noca/judge-python3:run'",
        ),
        sa.Column(
            "compile_cmd",
            sa.JSON(),
            nullable=True,
            comment="Command to compile the source as a list of strings, e.g. ['python3', '-m', 'py_compile', '/src.py']",
        ),
        sa.Column(
            "run_cmd",
            sa.JSON(),
            nullable=False,
            comment="Command to run the compiled code or script as a list of strings, e.g. ['python3', '-u', '/src.py']",
        ),
        sa.Column(
            "source_filename",
            sa.String(length=255),
            nullable=False,
            comment="Filename to use for the submitted source code when compiling/running, e.g. 'source.py'",
        ),
        sa.Column(
            "artifact_path",
            sa.String(length=255),
            nullable=False,
            comment="Path to the compiled artifact relative to the working directory, e.g. '/sandbox/source.py'",
        ),
        sa.Column(
            "artifact_is_source",
            sa.Boolean(),
            nullable=False,
            comment="Whether the source file itself is the artifact to run (i.e. no separate compilation output)",
        ),
        sa.Column("compile_timeout_s", sa.Float(), nullable=False, comment="Compilation timeout in seconds"),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "problem_categories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=48), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_problem_categories_name"),
    )
    op.create_table(
        "uber_admins",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "username",
            sa.String(length=80),
            nullable=False,
            comment="Identificador único do usuário, usado para login e geração de avatar",
        ),
        sa.Column(
            "fullname", sa.String(length=120), nullable=False, comment="Nome completo do usuário, usado para exibição"
        ),
        sa.Column("password_hash", sa.String(length=256), nullable=False, comment="Hash da senha do usuário"),
        sa.Column(
            "email_normalizado",
            sa.String(length=180),
            nullable=False,
            comment="E-mail normalizado do uberadmin, usado para comunicação apenas",
        ),
        sa.Column(
            "created_by_uberadmin",
            sa.String(length=36),
            nullable=True,
            comment="ID do uberadmin que criou este uberadmin, ou NULL se criado por script ou linha de comando",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_uber_admins_email_normalizado"), "uber_admins", ["email_normalizado"], unique=True)
    op.create_index(op.f("ix_uber_admins_username"), "uber_admins", ["username"], unique=True)
    op.create_table(
        "contests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("contest_name", sa.String(length=128), nullable=False, comment="Nome da competição"),
        sa.Column("contest_url", sa.String(length=256), nullable=False, comment="URL do site principal da competição"),
        sa.Column(
            "login_slug",
            sa.String(length=80),
            nullable=False,
            comment="Slug usado para login e identificação da competição",
        ),
        sa.Column(
            "owner_user_id", sa.String(length=36), nullable=True, comment="ID do usuário admin inicial da competição"
        ),
        sa.Column(
            "chief_judge_id",
            sa.String(length=36),
            nullable=True,
            comment="ID do judge que é o chief judge desta competição. Deve ter role=JUDGE e ser membro do contest.",
        ),
        sa.Column(
            "created_by_uberadmin_id",
            sa.String(length=36),
            nullable=False,
            comment="ID do uberadmin que criou a competição",
        ),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Data e hora de início da competição (UTC)",
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False, comment="Duração da competição em minutos"),
        sa.Column(
            "stop_answers_after",
            sa.Integer(),
            nullable=False,
            comment="Respostas param de ser enviadas após esse tempo (em minutos, a partir do início da competição)",
        ),
        sa.Column(
            "stop_updating_scoreboard",
            sa.Integer(),
            nullable=False,
            comment="O placar para de ser atualizado após esse tempo (em minutos, a partir do início da competição)",
        ),
        sa.Column("penalty", sa.Integer(), nullable=False, comment="Penalidade em minutos por submissão incorreta"),
        sa.Column(
            "clarifications_timeout_minutes",
            sa.Integer(),
            nullable=False,
            comment="Tempo em minutos um judge responder a uma clarification depois de obte-la",
        ),
        sa.Column(
            "tasks_timeout_minutes",
            sa.Integer(),
            nullable=False,
            comment="Tempo em minutos um membro do staff tem para concluir uma tarefa depois de obte-la",
        ),
        sa.Column(
            "review_timeout_minutes",
            sa.Integer(),
            server_default="10",
            nullable=False,
            comment="Tempo em minutos que um judge tem para confirmar um veredito apos adquirir o lock. 0 = desabilitado",
        ),
        sa.Column(
            "max_problem_file_size_bytes",
            sa.Integer(),
            nullable=False,
            comment="Tamanho máximo permitido para código fonte das submissões, em bytes. 0 significa sem limite",
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            comment="Indica se a competição está ativa. Inativa = inacessível a competidores, dados preservados",
        ),
        sa.Column(
            "autojudge_only",
            sa.Boolean(),
            nullable=False,
            comment="A resposta final a uma submissão é determinada apenas pelo autojudge",
        ),
        sa.Column(
            "show_limits",
            sa.Boolean(),
            nullable=False,
            comment="Os limites de tempo e memória dos problemas são exibidos aos competidores",
        ),
        sa.Column(
            "contest_timezone",
            sa.String(length=64),
            nullable=False,
            comment="Timezone da competição, usada para exibir horários locais aos competidores",
        ),
        sa.Column(
            "wa_penalty",
            sa.Integer(),
            nullable=False,
            comment="Penalidade em minutos por submissão incorreta (WA), adicionada ao tempo total para classificação",
        ),
        sa.Column(
            "accept_pe",
            sa.Boolean(),
            nullable=False,
            comment="Indica se a competição aceita PE como resultado correto (AC) ou se PE é considerado incorreto (WA)",
        ),
        sa.Column(
            "ce_adds_penalty",
            sa.Boolean(),
            nullable=False,
            comment="Indica se uma submissão com CE (Compilation Error) adiciona penalidade de tempo para a equipe",
        ),
        sa.Column(
            "release_scoreboard_after_end",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Unfreeze scoreboard after the contest ends, reveling final score.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["chief_judge_id"], ["users.id"], name="fk_contests_chief_judge_id", ondelete="SET NULL", use_alter=True
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uberadmin_id"],
            ["uber_admins.id"],
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], name="fk_contests_owner_user_id", use_alter=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_contests_chief_judge_id"), "contests", ["chief_judge_id"], unique=False)
    op.create_index(op.f("ix_contests_created_by_uberadmin_id"), "contests", ["created_by_uberadmin_id"], unique=False)
    op.create_index(op.f("ix_contests_login_slug"), "contests", ["login_slug"], unique=True)
    op.create_index(op.f("ix_contests_owner_user_id"), "contests", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_contests_start_time"), "contests", ["start_time"], unique=False)
    op.create_table(
        "problems",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("contest_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "time_limit_ms",
            sa.Integer(),
            nullable=False,
            comment="Base time limit in ms. Per-language overrides in problem_language_limits.",
        ),
        sa.Column(
            "memory_limit_kb",
            sa.Integer(),
            nullable=False,
            comment="Memory limit in KB, enforced by cgroup. Per-language overrides in problem_language_limits.",
        ),
        sa.Column(
            "pids_limit",
            sa.Integer(),
            nullable=False,
            comment="Max processes/threads via cgroup pids controller. Per-language overrides in problem_language_limits",
        ),
        sa.Column(
            "output_limit_in_bytes",
            sa.Integer(),
            nullable=True,
            comment="Max stdout bytes; NULL = no limit. Per-language overrides in problem_language_limits.",
        ),
        sa.Column("author", sa.String(length=256), nullable=True),
        sa.Column("notes", sa.String(length=512), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=False, comment="Balloon color, e.g. '#ff0000'"),
        sa.Column(
            "ordinal",
            sa.Integer(),
            nullable=False,
            comment="1-based display order within the contest. Label (A, B, C...) is derived from this.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("ordinal >= 1", name="ck_problems_ordinal_positive"),
        sa.ForeignKeyConstraint(["contest_id"], ["contests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contest_id", "ordinal", name="uq_problems_contest_ordinal"),
    )
    op.create_index(op.f("ix_problems_contest_id"), "problems", ["contest_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "username",
            sa.String(length=80),
            nullable=False,
            comment="Identificador único do usuário, usado para login e geração de avatar",
        ),
        sa.Column(
            "fullname", sa.String(length=120), nullable=False, comment="Nome completo do usuário, usado para exibição"
        ),
        sa.Column("password_hash", sa.String(length=256), nullable=False, comment="Hash da senha do usuário"),
        sa.Column(
            "role",
            _role_enum_ref(),
            nullable=False,
            comment="Função do usuário, que determina suas permissões no contest",
        ),
        sa.Column("com_foto", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "foto_base64", sa.Text(), nullable=True, comment="Foto original enviada pelo usuário, armazenada em base64"
        ),
        sa.Column(
            "avatar_base64",
            sa.Text(),
            nullable=True,
            comment="Avatar gerado a partir da foto original enviada pelo usuário, armazenado em base64",
        ),
        sa.Column(
            "foto_mime",
            sa.String(length=129),
            nullable=True,
            comment="MIME type da foto original enviada pelo usuário, usado para servir a foto corretamente",
        ),
        sa.Column(
            "dta_foto",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Data e hora da última atualização da foto do usuário, usada para controle de cache",
        ),
        sa.Column(
            "contest_id", sa.String(length=36), nullable=False, comment="ID do contest ao qual o usuário pertence"
        ),
        sa.Column(
            "created_by_admin_id",
            sa.String(length=36),
            nullable=True,
            comment="ID do usuário admin que criou este usuário",
        ),
        sa.Column(
            "created_by_uberadmin_id",
            sa.String(length=36),
            nullable=True,
            comment="ID do usuário uberadmin que criou este usuário",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(created_by_admin_id IS NOT NULL AND created_by_uberadmin_id IS NULL) OR (created_by_admin_id IS NULL AND created_by_uberadmin_id IS NOT NULL)",
            name="ck_users_exactly_one_creator",
        ),
        sa.ForeignKeyConstraint(["contest_id"], ["contests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_uberadmin_id"],
            ["uber_admins.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contest_id", "username", name="uq_users_contest_username"),
    )
    op.create_index(op.f("ix_users_contest_id"), "users", ["contest_id"], unique=False)
    op.create_index(op.f("ix_users_created_by_admin_id"), "users", ["created_by_admin_id"], unique=False)
    op.create_index(op.f("ix_users_created_by_uberadmin_id"), "users", ["created_by_uberadmin_id"], unique=False)
    op.create_table(
        "clarifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=False),
        sa.Column("judge_id", sa.String(length=36), nullable=True),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("question", sa.String(length=1024), nullable=False, comment="Text of the clarification question"),
        sa.Column(
            "is_contest_public",
            sa.Boolean(),
            nullable=False,
            comment="Should the clarification be visible to all teams in the contest",
        ),
        sa.Column("answer", sa.String(length=1024), nullable=True, comment="Text of the clarification answer"),
        sa.Column(
            "created_timestamp_seconds",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Seconds since contest start when the clarification was created.",
        ),
        sa.Column(
            "answered_at", sa.DateTime(timezone=True), nullable=True, comment="Time when the clarification was answered"
        ),
        sa.Column(
            "answered_timestamp_seconds",
            sa.Integer(),
            nullable=True,
            comment="Seconds since contest start when the clarification was answered.",
        ),
        sa.Column("hidden", sa.Boolean(), nullable=False, comment="Should the clarification be hidden from teams"),
        sa.Column(
            "hidden_by_judge_id",
            sa.String(length=36),
            nullable=True,
            comment="ID of the judge who hid the clarification",
        ),
        sa.Column(
            "hidden_by_admin_id",
            sa.String(length=36),
            nullable=True,
            comment="ID of the admin who hid the clarification",
        ),
        sa.Column(
            "hidden_at", sa.DateTime(timezone=True), nullable=True, comment="Time when the clarification was hidden"
        ),
        sa.Column(
            "hidden_timestamp_seconds",
            sa.Integer(),
            nullable=True,
            comment="Seconds since contest start when the clarification was hidden.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "hidden_by_judge_id IS NULL OR hidden_by_admin_id IS NULL",
            name="ck_clarifications_hidden_by_judge_xor_admin",
        ),
        sa.ForeignKeyConstraint(["hidden_by_admin_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["hidden_by_judge_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["judge_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clarifications_hidden_by_admin_id"), "clarifications", ["hidden_by_admin_id"], unique=False
    )
    op.create_index(
        op.f("ix_clarifications_hidden_by_judge_id"), "clarifications", ["hidden_by_judge_id"], unique=False
    )
    op.create_index(op.f("ix_clarifications_judge_id"), "clarifications", ["judge_id"], unique=False)
    op.create_index(op.f("ix_clarifications_problem_id"), "clarifications", ["problem_id"], unique=False)
    op.create_index(op.f("ix_clarifications_team_id"), "clarifications", ["team_id"], unique=False)
    op.create_table(
        "login_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("uberadmin_id", sa.String(length=36), nullable=True),
        sa.Column("dta_login", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(user_id IS NOT NULL AND uberadmin_id IS NULL) OR (user_id IS NULL AND uberadmin_id IS NOT NULL)",
            name="ck_login_history_exactly_one_actor",
        ),
        sa.ForeignKeyConstraint(["uberadmin_id"], ["uber_admins.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_login_history_uberadmin_id"), "login_history", ["uberadmin_id"], unique=False)
    op.create_index(op.f("ix_login_history_user_id"), "login_history", ["user_id"], unique=False)
    op.create_table(
        "problem_categories_map",
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["problem_categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("problem_id", "category_id"),
    )
    op.create_table(
        "problem_language_limits",
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column("language_id", sa.String(length=64), nullable=False),
        sa.Column("time_limit_ms", sa.Integer(), nullable=False),
        sa.Column("memory_limit_kb", sa.Integer(), nullable=False),
        sa.Column("pids_limit", sa.Integer(), nullable=False),
        sa.Column("output_limit_in_bytes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("problem_id", "language_id"),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "problem_id",
            sa.String(length=36),
            nullable=False,
            comment="Problem ID for this submission. RESTRICT on delete to prevent orphaned submissions.",
        ),
        sa.Column(
            "team_id",
            sa.String(length=36),
            nullable=False,
            comment="User ID of the team that made the submission. RESTRICT on delete to prevent orphaned submissions.",
        ),
        sa.Column(
            "language_id",
            sa.String(length=64),
            nullable=False,
            comment="Language key from languages table, e.g. 'gcc-c17'.",
        ),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column(
            "source_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hex digest of source_code for duplicate detection.",
        ),
        sa.Column("source_size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp_seconds",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Seconds since contest start when the submission was made. Used for ordering and tie-breaking.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["language_id"], ["languages.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "problem_id", "language_id", "source_hash", name="uq_submission_dedup"),
    )
    op.create_index(op.f("ix_submissions_language_id"), "submissions", ["language_id"], unique=False)
    op.create_index(op.f("ix_submissions_problem_id"), "submissions", ["problem_id"], unique=False)
    op.create_index(op.f("ix_submissions_source_hash"), "submissions", ["source_hash"], unique=False)
    op.create_index(op.f("ix_submissions_team_id"), "submissions", ["team_id"], unique=False)
    op.create_index(op.f("ix_submissions_timestamp_seconds"), "submissions", ["timestamp_seconds"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("team_id", sa.String(length=36), nullable=False),
        sa.Column("staff_id", sa.String(length=36), nullable=True),
        sa.Column("type", _task_enum_ref(), nullable=False),
        sa.Column(
            "problem_id",
            sa.String(length=36),
            nullable=True,
            comment="Problem ID for this task. NULL for SOS tasks. RESTRICT on delete to prevent orphaned tasks.",
        ),
        sa.Column(
            "created_timestamp_seconds",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Seconds since contest start when the task was created.",
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True, comment="Time when the task was finished"),
        sa.Column(
            "finished_timestamp_seconds",
            sa.Integer(),
            nullable=True,
            comment="Seconds since contest start when the task was finished.",
        ),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column(
            "source_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hex digest of source_code for duplicate detection.",
        ),
        sa.Column("source_size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["staff_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["team_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_problem_id"), "tasks", ["problem_id"], unique=False)
    op.create_index(op.f("ix_tasks_source_hash"), "tasks", ["source_hash"], unique=False)
    op.create_index(op.f("ix_tasks_staff_id"), "tasks", ["staff_id"], unique=False)
    op.create_index(op.f("ix_tasks_team_id"), "tasks", ["team_id"], unique=False)
    op.create_table(
        "test_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("problem_id", sa.String(length=36), nullable=False),
        sa.Column(
            "ordinal",
            sa.Integer(),
            nullable=False,
            comment="1-based execution order. Files: {problem_id}/{ordinal:03d}.in|out",
        ),
        sa.Column(
            "is_sample",
            sa.Boolean(),
            nullable=False,
            comment="Sample cases are shown to contestants; secret cases are not.",
        ),
        sa.Column("input_size_bytes", sa.Integer(), nullable=True),
        sa.Column("output_size_bytes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("ordinal >= 1", name="ck_test_cases_ordinal_positive"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("problem_id", "ordinal", name="uq_test_cases_problem_ordinal"),
    )
    op.create_index(op.f("ix_test_cases_problem_id"), "test_cases", ["problem_id"], unique=False)
    op.create_table(
        "submission_judgments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("status", _judgment_status_enum_ref(), nullable=False),
        sa.Column("autojudge_verdict", _verdict_enum_ref(), nullable=True),
        sa.Column("final_verdict", _verdict_enum_ref(), nullable=True),
        sa.Column("compile_log", sa.Text(), nullable=True),
        sa.Column("max_wall_time_ms", sa.Integer(), nullable=True),
        sa.Column("max_memory_kb", sa.Integer(), nullable=True),
        sa.Column("min_wall_time_ms", sa.Integer(), nullable=True),
        sa.Column("min_memory_kb", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("worker_id", sa.String(length=200), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "timestamp_seconds",
            sa.Integer(),
            nullable=True,
            comment="Seconds since contest start when this judgment was created. Null for pre-migration rows.",
        ),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_judgments_submission_id"), "submission_judgments", ["submission_id"], unique=False
    )
    op.create_table(
        "human_submission_confirmations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("judgment_id", sa.String(length=36), nullable=False),
        sa.Column("judge_id", sa.String(length=36), nullable=False),
        sa.Column("confirmed_verdict", _verdict_enum_ref(), nullable=False),
        sa.Column("is_chief_confirmation", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "timestamp_seconds",
            sa.Integer(),
            nullable=True,
            comment="Seconds since contest start when this confirmation was made. Null for pre-migration rows.",
        ),
        sa.ForeignKeyConstraint(["judge_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["judgment_id"], ["submission_judgments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("judgment_id", "judge_id", name="uq_confirmation_judgment_judge"),
    )
    op.create_index(
        op.f("ix_human_submission_confirmations_judge_id"), "human_submission_confirmations", ["judge_id"], unique=False
    )
    op.create_index(
        op.f("ix_human_submission_confirmations_judgment_id"),
        "human_submission_confirmations",
        ["judgment_id"],
        unique=False,
    )
    op.create_table(
        "submission_judgment_audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("judgment_id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("event_source", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("from_status", _judgment_status_enum_ref(), nullable=True),
        sa.Column("to_status", _judgment_status_enum_ref(), nullable=True),
        sa.Column("from_verdict", _verdict_enum_ref(), nullable=True),
        sa.Column("to_verdict", _verdict_enum_ref(), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "timestamp_seconds",
            sa.Integer(),
            nullable=True,
            comment="Seconds since contest start when this audit event occurred. Null for pre-migration rows.",
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["judgment_id"], ["submission_judgments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_judgment_audit_judgment_id"), "submission_judgment_audit", ["judgment_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_judgment_audit_submission_id"), "submission_judgment_audit", ["submission_id"], unique=False
    )
    op.create_table(
        "submission_test_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("judgment_id", sa.String(length=36), nullable=False),
        sa.Column("test_case_id", sa.String(length=36), nullable=False),
        sa.Column("verdict", _verdict_enum_ref(), nullable=False),
        sa.Column("wall_time_ms", sa.Integer(), nullable=True),
        sa.Column("memory_kb", sa.Integer(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("stdout_excerpt", sa.Text(), nullable=True),
        sa.Column("stderr_excerpt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["judgment_id"], ["submission_judgments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["test_case_id"], ["test_cases.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("judgment_id", "test_case_id", name="uq_submission_test_results_case"),
    )
    op.create_index(
        op.f("ix_submission_test_results_judgment_id"), "submission_test_results", ["judgment_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_test_results_test_case_id"), "submission_test_results", ["test_case_id"], unique=False
    )
    op.create_table(
        "verdict_overrides",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("judgment_id", sa.String(length=36), nullable=False),
        sa.Column("overridden_by", sa.String(length=36), nullable=False),
        sa.Column("original_verdict", _verdict_enum_ref(), nullable=False),
        sa.Column("new_verdict", _verdict_enum_ref(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "timestamp_seconds",
            sa.Integer(),
            nullable=True,
            comment="Seconds since contest start when this override was applied. Null for pre-migration rows.",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["judgment_id"], ["submission_judgments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["overridden_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verdict_overrides_judgment_id"), "verdict_overrides", ["judgment_id"], unique=False)
    op.create_index(op.f("ix_verdict_overrides_overridden_by"), "verdict_overrides", ["overridden_by"], unique=False)
    op.create_index(op.f("ix_verdict_overrides_submission_id"), "verdict_overrides", ["submission_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verdict_overrides_submission_id"), table_name="verdict_overrides")
    op.drop_index(op.f("ix_verdict_overrides_overridden_by"), table_name="verdict_overrides")
    op.drop_index(op.f("ix_verdict_overrides_judgment_id"), table_name="verdict_overrides")
    op.drop_table("verdict_overrides")
    op.drop_index(op.f("ix_submission_test_results_test_case_id"), table_name="submission_test_results")
    op.drop_index(op.f("ix_submission_test_results_judgment_id"), table_name="submission_test_results")
    op.drop_table("submission_test_results")
    op.drop_index(op.f("ix_submission_judgment_audit_submission_id"), table_name="submission_judgment_audit")
    op.drop_index(op.f("ix_submission_judgment_audit_judgment_id"), table_name="submission_judgment_audit")
    op.drop_table("submission_judgment_audit")
    op.drop_index(op.f("ix_human_submission_confirmations_judgment_id"), table_name="human_submission_confirmations")
    op.drop_index(op.f("ix_human_submission_confirmations_judge_id"), table_name="human_submission_confirmations")
    op.drop_table("human_submission_confirmations")
    op.drop_index(op.f("ix_submission_judgments_submission_id"), table_name="submission_judgments")
    op.drop_table("submission_judgments")
    op.drop_index(op.f("ix_test_cases_problem_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_index(op.f("ix_tasks_team_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_staff_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_source_hash"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_problem_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_submissions_timestamp_seconds"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_team_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_source_hash"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_problem_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_language_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_table("problem_language_limits")
    op.drop_table("problem_categories_map")
    op.drop_index(op.f("ix_login_history_user_id"), table_name="login_history")
    op.drop_index(op.f("ix_login_history_uberadmin_id"), table_name="login_history")
    op.drop_table("login_history")
    op.drop_index(op.f("ix_clarifications_team_id"), table_name="clarifications")
    op.drop_index(op.f("ix_clarifications_problem_id"), table_name="clarifications")
    op.drop_index(op.f("ix_clarifications_judge_id"), table_name="clarifications")
    op.drop_index(op.f("ix_clarifications_hidden_by_judge_id"), table_name="clarifications")
    op.drop_index(op.f("ix_clarifications_hidden_by_admin_id"), table_name="clarifications")
    op.drop_table("clarifications")
    op.drop_index(op.f("ix_users_created_by_uberadmin_id"), table_name="users")
    op.drop_index(op.f("ix_users_created_by_admin_id"), table_name="users")
    op.drop_index(op.f("ix_users_contest_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_problems_contest_id"), table_name="problems")
    op.drop_table("problems")
    op.drop_index(op.f("ix_contests_start_time"), table_name="contests")
    op.drop_index(op.f("ix_contests_owner_user_id"), table_name="contests")
    op.drop_index(op.f("ix_contests_login_slug"), table_name="contests")
    op.drop_index(op.f("ix_contests_created_by_uberadmin_id"), table_name="contests")
    op.drop_index(op.f("ix_contests_chief_judge_id"), table_name="contests")
    op.drop_table("contests")
    op.drop_index(op.f("ix_uber_admins_username"), table_name="uber_admins")
    op.drop_index(op.f("ix_uber_admins_email_normalizado"), table_name="uber_admins")
    op.drop_table("uber_admins")
    op.drop_table("problem_categories")
    op.drop_table("languages")
    bind = op.get_bind()
    _create_verdict_enum().drop(bind, checkfirst=True)
    _create_judgment_status_enum().drop(bind, checkfirst=True)
    _create_task_enum().drop(bind, checkfirst=True)
    _create_role_enum().drop(bind, checkfirst=True)
    # ### end Alembic commands ###
