"""Add site to contest and user

Revision ID: 8cb3a127b286
Revises: 73c77ae6a2b0
Create Date: 2026-04-04 00:22:30.655369

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8cb3a127b286'
down_revision: str | Sequence[str] | None = '73c77ae6a2b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sitename', sa.String(length=128), nullable=False, comment='Name of site contest (university campus, city...)'),
    sa.Column('sitename_normalized', sa.String(length=128), nullable=False, comment='Lowercased site name for contest-scoped uniqueness'),
    sa.Column('contest_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'id', name='uq_sites_contest_id_id'),
    sa.UniqueConstraint('contest_id', 'sitename_normalized', name='uq_sites_contest_sitename_normalized')
    )
    op.create_index(op.f('ix_sites_contest_id'), 'sites', ['contest_id'], unique=False)
    op.create_index(op.f('ix_sites_sitename'), 'sites', ['sitename'], unique=False)
    op.create_foreign_key('fk_contests_chief_judge_id', 'contests', 'users', ['chief_judge_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_contests_owner_user_id', 'contests', 'users', ['owner_user_id'], ['id'], use_alter=True)
    op.add_column('users', sa.Column('site_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_foreign_key(None, 'users', 'sites', ['site_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_contest_id_site_id', 'users', 'sites', ['contest_id', 'site_id'], ['contest_id', 'id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_contest_id_site_id', 'users', type_='foreignkey')
    # The FK users.site_id → sites.id was created without an explicit name; look it up at runtime.
    inspector = sa.inspect(op.get_bind())
    site_id_fk = next(
        (fk["name"] for fk in inspector.get_foreign_keys("users")
         if fk.get("referred_table") == "sites" and fk.get("constrained_columns") == ["site_id"]),
        None,
    )
    if site_id_fk:
        op.drop_constraint(site_id_fk, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_column('users', 'site_id')
    op.drop_constraint('fk_contests_owner_user_id', 'contests', type_='foreignkey')
    op.drop_constraint('fk_contests_chief_judge_id', 'contests', type_='foreignkey')
    op.drop_index(op.f('ix_sites_sitename'), table_name='sites')
    op.drop_index(op.f('ix_sites_contest_id'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
