"""arena: Show source instead of author

Revision ID: b6bade6eebf0
Revises: 202605170001
Create Date: 2026-05-19 17:08:26.425113

"""

#  NOCA -- Next Online Contest Administrator
#  Copyright (c) 2026 Daniel Correa Lobato <daniel@lobato.org>
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b6bade6eebf0"
down_revision: str | Sequence[str] | None = "202605170001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "arena_problems",
        sa.Column(
            "hide_author_show_source",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Should we display source of problem instead of author's name?",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("arena_problems", "hide_author_show_source")
    # ### end Alembic commands ###
