#  NOCA -- Next Online Contest Administrator
#  Copyright (c) 2026 Daniel Correa Lobato <daniel@lobato.org>
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
"""AI credits

Revision ID: 3dd3ca1867a9
Revises: 202605260001
Create Date: 2026-05-27 22:47:18.541650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd3ca1867a9'
down_revision: Union[str, Sequence[str], None] = '202605260001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arena_users',
                  sa.Column('ai_backend_credits',
                            sa.Integer(),
                            server_default=sa.text('0'),
                            nullable=False,
                            comment='Number of AI credits available to use backend API Key')
                  )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arena_users', 'ai_backend_credits')
    # ### end Alembic commands ###
