#  NOCA -- Next Online Contest Administrator
#  Copyright (c) 2026 Daniel Correa Lobato <daniel@lobato.org>
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

"""Core table definitions for Arena users, backup 2FA codes, and login history."""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    Integer,
    String,
    Table,
    Text,
    text,
)
from sqlalchemy import Enum as SAEnum

from shared.enumerations import ArenaRole

from .._base import _created_at_column, _id_column, _updated_at_column, _utcnow, metadata
from ..custom_types import EncryptedString

_login_history_id_type = BigInteger().with_variant(Integer, "sqlite")

arena_users = Table(
    "arena_users",
    metadata,
    _id_column(),
    Column("nome", String(120), nullable=False, comment="Full display name of the arena user"),
    Column("dta_nascimento", Date, nullable=True, comment="Date of birth"),
    Column(
        "email_normalizado",
        String(180),
        unique=True,
        nullable=False,
        comment="Normalised email address; used as the primary login identifier",
    ),
    Column(
        "email_responsavel_legal",
        String(255),
        nullable=True,
        comment="Parent or legal guardian email for users who require consent",
    ),
    Column(
        "consentimento_responsavel",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Parent or legal guardian consent has been confirmed",
    ),
    Column(
        "dta_consentimento_responsavel",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when parent or legal guardian consent was confirmed",
    ),
    Column(
        "aceitou_termos_privacidade",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="User explicitly accepted the Terms of Service and Privacy Policy during signup",
    ),
    Column(
        "dta_aceitacao_termos_privacidade",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp (UTC) when the user accepted the Terms of Service and Privacy Policy",
    ),
    Column("password_hash", String(256), nullable=False, comment="Werkzeug password hash"),
    Column(
        "role",
        SAEnum(ArenaRole, values_callable=lambda e: [m.value for m in e]),
        nullable=False,
        server_default=text("'ARENA_USER'"),
        comment="Arena role: ARENA_ADMIN, ARENA_JUDGE, or ARENA_USER",
    ),
    Column(
        "can_edit",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="User may add/edit problems on the Arena problem base (admins always may)",
    ),
    Column(
        "ranking_visible",
        Boolean,
        nullable=False,
        default=True,
        server_default=text("true"),
        comment="User consents to appear in the public ranking; rating is still computed when False",
    ),
    Column(
        "ativo",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Account is active; user is allowed to log in",
    ),
    Column(
        "dta_ativacao_conta",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when the account was activated",
    ),
    Column(
        "email_confirmado",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Email address has been confirmed; required before first login",
    ),
    Column(
        "dta_validacao_email",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when the email address was confirmed",
    ),
    Column(
        "dta_ultima_alteracao_senha",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of the last password change",
    ),
    Column(
        "ultimo_login",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of the most recent successful login",
    ),
    Column(
        "com_foto",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="True when the user has uploaded a profile photo",
    ),
    Column(
        "foto_base64",
        Text,
        nullable=True,
        default=None,
        comment="Original photo stored as base64-encoded string",
    ),
    Column(
        "avatar_base64",
        Text,
        nullable=True,
        default=None,
        comment="Resized avatar derived from the original photo, base64-encoded",
    ),
    Column(
        "foto_mime",
        String(129),
        nullable=True,
        default=None,
        comment="MIME type of the stored photo (e.g. image/jpeg)",
    ),
    Column(
        "dta_foto",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp of the last photo upload",
    ),
    Column(
        "usa_2fa",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="TOTP two-factor authentication is enabled for this account",
    ),
    Column(
        "dta_mudanca_2fa",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when 2FA was last enabled or disabled",
    ),
    Column(
        "_otp_secret",
        EncryptedString(length=500),
        nullable=True,
        default=None,
        comment="Encrypted TOTP secret used for 2FA code generation",
    ),
    Column(
        "_ai_api_key",
        EncryptedString(length=500),
        nullable=True,
        default=None,
        comment="Encrypted AI provider API key for AI-assisted code submission",
    ),
    Column(
        "ai_backend_credits",
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
        comment="Number of AI credits available to use backend API Key",
    ),
    Column(
        "ultimo_otp",
        String(6),
        nullable=True,
        default=None,
        comment="Last used OTP code; prevents replay attacks within the same time window",
    ),
    Column(
        "precisa_trocar_senha",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="Forces a password change on the next login",
    ),
    Column(
        "dta_marcacao_troca_senha",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when the forced password change flag was set",
    ),
    Column(
        "session_version",
        Integer,
        nullable=False,
        default=0,
        server_default=text("0"),
        comment="Incremented on each password change; JWT tokens carrying an older version are rejected",
    ),
    Column(
        "dta_rating_update",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when the user's rating was computed",
    ),
    Column(
        "user_rating", Integer, nullable=True, default=0, server_default=text("0"), comment="User's rating computed"
    ),
    Column(
        "solved_problems",
        Integer,
        nullable=True,
        default=0,
        server_default=text("0"),
        comment="Number of problems solved",
    ),
    Column("country_code", String(2), nullable=True, comment="ISO 3166-1 alpha-2 country code"),
    Column("subdivision_code", String(16), nullable=True, comment="ISO 3166-2 subdivision code"),
    Column(
        "affiliation_id",
        String(36),
        ForeignKey("arena_affiliations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="Optional affiliation selected by the Arena user",
    ),
    Column(
        "preferred_language_id",
        String(64),
        ForeignKey("languages.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="User's preferred programming language for submissions",
    ),
    Column(
        "prefered_language",
        String(5),
        nullable=False,
        default="en-US",
        server_default=text("'en-US'"),
        comment="User's preferred interface and AI-response language locale",
    ),
    CheckConstraint(
        "prefered_language IN ('en-US', 'pt-BR')",
        name="ck_arena_users_prefered_language",
    ),
    _created_at_column(),
    _updated_at_column(),
)

arena_affiliations = Table(
    "arena_affiliations",
    metadata,
    _id_column(),
    Column("name", String(200), nullable=False, unique=True, index=True, comment="Affiliation display name"),
    Column("country_code", String(2), nullable=True, comment="ISO 3166-1 alpha-2 country code"),
    Column("subdivision_code", String(16), nullable=True, comment="ISO 3166-2 subdivision code"),
    Column("url", String(500), nullable=True, comment="Affiliation public URL"),
    Column("logo_base64", Text, nullable=True, comment="Affiliation logo stored as base64-encoded image bytes"),
    Column("logo_mime", String(129), nullable=True, comment="MIME type of the affiliation logo"),
    Column(
        "logo_thumbnail_base64",
        Text,
        nullable=True,
        comment="Affiliation logo thumbnail (64x64 px) stored as base64-encoded image bytes",
    ),
    Column(
        "rating",
        Integer,
        nullable=True,
        default=0,
        server_default=text("0"),
        comment="Affiliation combined rating computed from member scores using geometric weighting",
    ),
    Column(
        "dta_rating_update",
        DateTime(timezone=True),
        nullable=True,
        comment="Timestamp when the affiliation rating was last computed",
    ),
    Column(
        "exclude_from_ranking",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="When true, excludes the affiliation from the public ranking and rating computation",
    ),
    _created_at_column(),
    _updated_at_column(),
)

arena_backup_2fa = Table(
    "arena_backup_2fa",
    metadata,
    _id_column(),
    Column(
        "arena_user_id",
        String(36),
        ForeignKey("arena_users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Arena user who owns this backup code",
    ),
    Column(
        "hash_codigo",
        String(256),
        nullable=False,
        comment="Werkzeug hash of the one-time backup code",
    ),
    Column(
        "utilizado",
        Boolean,
        nullable=False,
        default=False,
        server_default=text("false"),
        comment="True when this backup code has already been consumed",
    ),
    Column(
        "dta_uso",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Timestamp when this code was consumed",
    ),
    Column(
        "dta_para_remocao",
        DateTime(timezone=True),
        nullable=True,
        default=None,
        comment="Scheduled deletion timestamp for used codes",
    ),
    _created_at_column(),
)

arena_login_history = Table(
    "arena_login_history",
    metadata,
    Column(
        "id",
        _login_history_id_type,
        Identity(),
        primary_key=True,
        autoincrement=True,
        comment="Sequential login event identifier",
    ),
    Column(
        "arena_user_id",
        String(36),
        ForeignKey("arena_users.id", ondelete="CASCADE"),
        nullable=False,
        comment="Arena user who performed this login",
    ),
    Column(
        "dta_login",
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        comment="Timestamp of the login event",
    ),
    Column("ip_address", String(45), nullable=True, comment="Client IP address (IPv4 or IPv6)"),
    Column("location", String(128), nullable=True, comment="Geographic location derived from IP"),
    Column("user_agent", Text, nullable=True, comment="HTTP User-Agent header"),
    Column(
        "mode",
        String(32),
        nullable=True,
        comment="Authentication method used: password, 2fa, backup_code",
    ),
    Index(
        "ix_arena_login_history_user_login",
        "arena_user_id",
        "dta_login",
    ),
)
